config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks
  # get "tasks/new", to: 'tasks#new', as: 'new_task' # Show create FORM
  # post "tasks", to: 'tasks#create'

  # get 'tasks', to: 'tasks#index'
  # get 'tasks/:id', to: 'tasks#show', as: 'task'

  # get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task' # Show edit FORM
  # patch 'tasks/:id', to: 'tasks#update'

  # delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save!
    redirect_to task_path(task)
  end

  def edit
  end

  def update
    @task.update!(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

<%=link_to "Back home", tasks_path%>

app/views/tasks/index.html.erb
<h1 class="text-center m-5">My Tasks</h1>

<div class="container text-center mt-5">
<ul class="list-display-none">
  <%@tasks.each do |task|%>
    <li class="p-3 text-decoration-none ">
    <input type="checkbox">
    <%=link_to task.title, task_path(task), class: 'fw-bold'%>
    <%= link_to 'remove', task_path(task), data: { turbo_method: 'delete'}, class: 'btn btn-danger' %>
    </li>
  <%end%>
</ul>
<p>
  <%= link_to 'Add new Task', new_task_path, class: 'btn btn-success' %>
</p>
</div>

app/views/tasks/new.html.erb
<h1>Add New Task</h1>

<%= render 'form', task: @task %>

 <%=link_to "Back home", tasks_path%>

app/views/tasks/show.html.erb
<h1>Description</h1>

<p>Task: <%=@task.title%></p>
<p>Details: <%=@task.details%></p>
<p>Completed: <%=@task.completed%></p>

<div>
  <div>
    <%= link_to 'Edit This Task', edit_task_path(@task) %>
  </div>
  <div>
    <%=link_to "Back home", tasks_path%>
  </div>
</div>